<script lang="ts">
import {Field, Select, SegmentedControl, Button, Badge, EmptyState, StatGroup} from '../../design-system/svelte';
import FullExamples from './FullExamples.svelte';
import Recipe from './Recipe.svelte';import CodeExample from './CodeExample.svelte';
import {recipes} from './recipes';import {baselines} from './baselines';
let selected=$state('navigation'),query=$state(''),baselineQuery=$state(''),variant=$state('light'),scenario=$state('01-09-scene-selected');
const filtered=$derived(recipes.filter(r=>`${r.title} ${r.description} ${r.components.join(' ')}`.toLowerCase().includes(query.toLowerCase())));
const scenarios=baselines.filter(b=>b.variant==='light');
const available=$derived(scenarios.filter(b=>`${b.scenario} ${b.expect}`.toLowerCase().includes(baselineQuery.toLowerCase())));
const selectedScenario=$derived(available.some(b=>b.scenario===scenario)?scenario:available[0]?.scenario);
const baseline=$derived(baselines.find(b=>b.scenario===selectedScenario&&b.variant===variant));
const label=(s:string)=>s.replace(/^\d+-\d+-/,'').replaceAll('-',' ');
function choose(id:string){selected=id;scenario=recipes.find(r=>r.id===id)!.baseline;baselineQuery='';}
</script>
<div class="press-app ac-catalog">
<div class="ac-intro"><div><p class="ac-overline"><span class="press-brand-name">kindling</span> / application · Svelte 5</p><h3>From first scene<br/>to final draft.</h3><p class="ac-intro-copy">The pieces of a quieter writing workspace. Explore their behavior, take the Svelte source, and connect them to your app.</p><div class="ka-row"><a class="ac-text-link" href="#app-component-examples">All 22 component examples ↓</a><a class="ac-text-link" href="#app-composition-recipes">Composition recipes ↓</a><a class="ac-text-link" href="docs/APPLICATION_COMPONENTS.md">Component API guide ↗</a><a class="ac-text-link" href="#app-baselines">Browse visual references ↓</a></div></div><StatGroup items={[{value:22,label:'Svelte components'},{value:12,label:'Working recipes'},{value:49,label:'Baseline scenarios'},{value:3,label:'Reference variants'}]}/></div>
<FullExamples/>
<section id="app-composition-recipes" aria-label="Composition recipes">
<div class="ac-recipe-heading"><div><p class="ac-overline">Putting the pieces together</p><h3>Application recipes.</h3><p>Explore the same components in twelve larger compositions.</p></div></div>
<div class="ac-find"><Field label="Find a recipe" type="search" placeholder="Search buttons, dialogs, tags…" bind:value={query}/><p class="ka-help" role="status">{filtered.length} of {recipes.length} recipes</p></div>
<nav class="ac-recipe-nav" aria-label="Application recipes">{#each filtered as r}<button type="button" aria-current={selected===r.id?'true':undefined} onclick={()=>choose(r.id)}><span class="ac-recipe-number">{String(recipes.indexOf(r)+1).padStart(2,'0')}</span><span class="od-field"><strong>{r.title}</strong><small>{r.components.slice(0,2).join(' · ')}</small></span><span aria-hidden="true">↗</span></button>{/each}</nav>
{#if !filtered.length}<EmptyState title="No matching components" description="Try a component name such as Field or Dialog."><Button variant="secondary" onclick={()=>query=''}>Clear search</Button></EmptyState>{/if}
{#each recipes as r}<section class="ac-recipe" hidden={r.id!==selected} aria-labelledby={`app-recipe-${r.id}`}><header class="ac-recipe-heading"><div><p class="ac-overline">Live recipe / {String(recipes.indexOf(r)+1).padStart(2,'0')}</p><h3 id={`app-recipe-${r.id}`}>{r.title}</h3><p>{r.description}</p></div><Badge label="Svelte 5"/></header><div class="ac-specimen"><Recipe kind={r.id}/></div><div class="ac-recipe-meta"><p><strong>Components</strong> {r.components.join(' · ')}</p><a href="#app-baselines" onclick={()=>{scenario=r.baseline;baselineQuery='';}}>View mapped baseline ↓</a></div><CodeExample code={r.code}/></section>{/each}
</section>
<section id="app-baselines" class="ac-baselines" aria-labelledby="app-baseline-heading"><header class="ac-recipe-heading"><div><p class="ac-overline">Visual reference archive</p><h3 id="app-baseline-heading">The app, as captured.</h3><p>Historical QA captures, not current brand specimens. They may show retired spelling. Current text and artwork always use lowercase kindling.</p></div><Badge label="147 originals"/></header><div class="ac-baseline-controls"><Field label="Find a baseline" type="search" bind:value={baselineQuery} placeholder="Try export, reference, or shortcut"/>{#if available.length}<Select label="Scenario" value={selectedScenario} onChange={(v)=>scenario=v} options={available.map(b=>({value:b.scenario,label:`${b.scenario.slice(0,5)} · ${label(b.scenario)}`}))}/>{/if}<SegmentedControl label="Capture variant" bind:value={variant} options={[{value:'light',label:'Light'},{value:'dark',label:'Dark'},{value:'narrow',label:'Narrow'}]}/></div>
{#if baseline}<figure class="ac-reference"><a class="ac-reference-frame" href={`reference/application/baselines/${baseline.file}`} target="_blank" rel="noreferrer" aria-label={`Open full ${label(baseline.scenario)} ${baseline.variant} baseline`}><img src={`reference/application/baselines/${baseline.file}`} width={baseline.width} height={baseline.height} loading="lazy" decoding="async" alt={`kindling ${label(baseline.scenario)}, ${baseline.variant} baseline. ${baseline.expect}`}/></a><figcaption><div class="ka-between"><strong>{label(baseline.scenario)}</strong><span>{baseline.width} × {baseline.height} px · 2× source</span></div><p>{baseline.expect}</p><div class="ka-between"><p class="ka-help">Mapped families: {baseline.families.join(', ')}.</p><a class="ac-text-link" href={`reference/application/baselines/${baseline.file}`} target="_blank" rel="noreferrer">Open original ↗</a></div></figcaption></figure>{:else}<EmptyState title="No matching baselines" description="Clear the search to browse all 49 scenarios."><Button variant="secondary" onclick={()=>baselineQuery=''}>Clear search</Button></EmptyState>{/if}
<p class="ac-footnote">Reference inputs from the supplied QA suite; these are not screenshots or acceptance results for this library. <a href="docs/APPLICATION_SOURCES.json">Source manifest ↗</a></p></section>
<div class="ac-adoption"><p class="ac-overline">Adopt at your own pace</p><h3>Keep the app. Share the pieces.</h3><p>Start with one field, button, or dialog. Existing stores, command dispatch, Tauri calls, and editor logic stay in your app. The guide shows the adapters between them.</p><a class="ac-text-link" href="docs/APPLICATION_COMPONENTS.md#incremental-adoption">Read the integration notes ↗</a></div>
</div>
