<script lang="ts">
import { Button, IconButton, Field, Checkbox, Select, SegmentedControl, Tabs, Badge, TagPicker, Progress, EmptyState, Notice, Dialog, Menu, CommandPalette, NavigationTree, Panel, BeatItem, ManuscriptSurface, StatGroup, ShortcutRecorder, SearchResults } from '../../design-system/svelte';
import WritingExample from './WritingExample.svelte';
import type { TreeNode } from '../../design-system/svelte';
let {kind}:{kind:string}=$props();
const options=(...labels:string[])=>labels.map(label=>({label,value:label}));
let title=$state('The Beginning'), error=$state(''), busy=$state(false), message=$state('');
let dialog=$state(false), confirm=$state(false), commandOpen=$state(false), deleted=$state(false);
let scene=$state('beginning');
let tags=$state(['character']), tagQuery=$state('');
let theme=$state('System'), guidance=$state(true), customType=$state('Text'), customName=$state('Point of view'), customValue=$state('Mara');
let refName=$state(''),refDescription=$state(''),refError=$state(''),refQuery=$state('');
let refs=$state<{id:string;title:string;excerpt:string}[]>([]);
let shortcut=$state('Meta+F'), commandFilter=$state('');
let find=$state('lantern'), replacement=$state('light'), previous=$state<string|null>(null);
let text=$state('Mara reached the harbor. The lantern shone over the water. She carried the letter home.');
let words=$state(30),snapshots=$state<string[]>([]),historyOpen=$state(true);
let reviewTab=$state('Review'),comments=$state<string[]>([]),comment=$state('');
let format=$state('Web / HTML'),profile=$state('Agent submission'),selection=$state<string[]>([]),exportNav=$state('content'),savedProfile=$state('Agent submission');
let nodes=$state<TreeNode[]>([{id:'act-1',label:'Act 1',meta:'30 words',children:[{id:'beginning',label:'The Beginning',meta:'15 words'},{id:'discovery',label:'Discovery',meta:'15 words'}]},{id:'act-2',label:'Act 2',meta:'0 words',children:[{id:'turning',label:'Turning Point',meta:'0 words'}]},{id:'act-3',label:'Act 3',meta:'0 words',children:[{id:'finale',label:'Finale',meta:'0 words'}]}]);
const results=$derived(find.trim()&&text.toLowerCase().includes(find.toLowerCase())?[{id:'beginning',title:'The Beginning',path:'Act 1 / Opening scene',excerpt:text}]:[]);
const filteredRefs=$derived(refs.filter(r=>`${r.title} ${r.excerpt}`.toLowerCase().includes(refQuery.toLowerCase())));
const commands=[{id:'new',label:'New scene',group:'Writing',shortcut:'⌘N',keywords:['create','scene']},{id:'find',label:'Find in scene',group:'Edit',shortcut:'⌘F',keywords:['search']},{id:'settings',label:'Open settings',group:'Application',shortcut:'⌘,',keywords:['preferences']}];
async function save(e:SubmitEvent){e.preventDefault();error=title.trim()?'':'Enter a chapter title to continue.';message='';if(error)return;busy=true;await new Promise(r=>setTimeout(r,400));busy=false;message=`“${title.trim()}” saved in this specimen.`;}
function addReference(){if(!refName.trim()){refError='Enter a name for the character.';return;}refs=[...refs,{id:`ref-${refs.length+1}`,title:refName.trim(),excerpt:refDescription||'No description added.'}];refName='';refDescription='';refError='';dialog=false;}
function replace(){previous=text;const q=find.toLowerCase();let cursor=0;let at=text.toLowerCase().indexOf(q);let output='';while(q&&at>=0){output+=text.slice(cursor,at)+replacement;cursor=at+q.length;at=text.toLowerCase().indexOf(q,cursor);}text=output+text.slice(cursor);confirm=false;message='Replacement applied to the sample text.';}
function selectChapter(label:string){selection=selection.includes(label)?selection.filter(x=>x!==label):[...selection,label];}
</script>

{#if kind==='actions'}
<div class="ac-two"><form class="od-stack ac-space" onsubmit={save} novalidate><Field label="Chapter title" bind:value={title} required {error} disabled={busy} helper="Clear the title and leave the field to see its required state."/><div class="ka-row"><Button type="submit" {busy}>{busy?'Saving…':'Save title'}</Button><Button variant="secondary" onclick={()=>{title='The Beginning';error='';message='';}}>Reset</Button></div>{#if message}<Notice title="Title updated" {message} tone="success"/>{/if}</form><div class="od-stack ac-space"><p class="ac-overline">Action hierarchy</p><div class="ka-row"><Button variant="secondary" onclick={()=>dialog=true}>Open dialog</Button><IconButton label="Open scene actions" icon="ellipsis" onclick={()=>dialog=true}/></div><div class="ka-row"><Button disabled>Nothing to export</Button><Button variant="danger" onclick={()=>confirm=true}>Delete scene</Button></div><div class="ka-row"><Badge label="Draft"/><Badge label="Fixed" tone="accent"/><Badge label="Saved" tone="success"/></div></div></div>
<Dialog bind:open={dialog} title="Scene details"><p>Actions inherit Press tokens and remain native, keyboard-operable buttons.</p>{#snippet footer()}<Button onclick={()=>dialog=false}>Done</Button>{/snippet}</Dialog>
<Dialog bind:open={confirm} title="Delete sample scene?"><p>This affects only the specimen. The example can be restored immediately.</p>{#snippet footer()}<Button variant="secondary" onclick={()=>confirm=false}>Cancel</Button><Button variant="danger" onclick={()=>{confirm=false;message='Sample scene deleted. Use Reset to restore the initial title.';title='';}}>Delete scene</Button>{/snippet}</Dialog>
{:else if kind==='navigation'}
<div class="ac-workspace"><div class="ac-app-sidebar"><div class="ka-between"><h4>Simple Story</h4><IconButton icon="plus" label="Add a sample scene" onclick={()=>{const id=`scene-${nodes[0].children!.length}`;nodes=nodes.map((n,i)=>i? n:{...n,children:[...n.children!,{id,label:'New scene',meta:'0 words'}]});scene=id;}}/></div><Progress label="Today’s writing" value={30} max={500}/><NavigationTree label="Manuscript chapters" {nodes} bind:selected={scene}/></div><div class="ac-workspace-main"><p class="ac-overline">Selected scene</p><h3>{nodes.flatMap(n=>n.children||[]).find(n=>n.id===scene)?.label}</h3><p>Choose a scene in the sidebar. Expand or collapse an act, or add a scene using the plus button.</p><div class="ka-row"><Badge label="Draft"/><Badge label="Fixed" tone="accent"/></div><EmptyState title="Room for a new beginning" description="The writing surface follows the selected scene." icon="book-open"/></div></div>
{:else if kind==='writing'}
<WritingExample/>
{:else if kind==='tags'}
<div class="ac-two"><TagPicker label="Scene tags" options={[{label:'Character',value:'character'},{label:'Setting',value:'setting'},{label:'Plot thread',value:'plot'},{label:'Research',value:'research'}]} bind:value={tags}/><Panel title="Metadata" subtitle="Labels accompany every status color"><div class="od-stack ac-space"><div class="ka-row"><Badge label="Draft"/><Badge label="Needs review" tone="warning"/><Badge label="Approved" tone="success"/></div><p>{tags.length} {tags.length===1?'tag':'tags'} selected for this scene.</p><p class="ka-help">Pass existing tag IDs and receive selected IDs through onChange. Your app keeps ownership of tag creation and persistence.</p></div></Panel></div>
{:else if kind==='references'}
<Panel title="References" subtitle="Characters and locations">{#snippet actions()}<Button variant="secondary" onclick={()=>dialog=true}>Add character</Button>{/snippet}<div class="od-stack ac-space"><Field label="Filter references" type="search" bind:value={refQuery}/>{#if !refs.length}<EmptyState title="No characters yet" description="Add a character to see the populated reference list." icon="book-open"/>{:else}<SearchResults items={filteredRefs} query={refQuery} onSelect={(id)=>{const r=refs.find(x=>x.id===id);message=r?`${r.title}: ${r.excerpt}`:'';}}/>{/if}{#if message}<Notice title="Reference details" {message}/>{/if}</div></Panel>
<Dialog bind:open={dialog} title="Add character"><div class="od-stack ac-space"><Field label="Name" bind:value={refName} required error={refError}/><Field label="Description" multiline bind:value={refDescription}/></div>{#snippet footer()}<Button variant="secondary" onclick={()=>dialog=false}>Cancel</Button><Button onclick={addReference}>Save character</Button>{/snippet}</Dialog>
{:else if kind==='settings'}
<div class="ac-two"><div class="od-stack ac-space"><h4>Appearance & guidance</h4><SegmentedControl label="Appearance preference" options={options('Dark','Light','System')} bind:value={theme}/><p class="ka-help">Selected: {theme}. This example emits a preference; use the reference’s theme control to change the surrounding catalog.</p><Checkbox label="Show guidance tips" bind:checked={guidance} helper="Contextual hints for new writing workflows."/>{#if guidance}<Notice title="A little guidance" message="Start with one scene. You can organize it into an act later."/>{/if}</div><div class="od-stack ac-space"><h4>Custom field</h4><Field label="Field name" bind:value={customName}/><Select label="Field type" options={options('Text','Number','Date','Selection','Checkbox')} bind:value={customType}/>{#if customType==='Checkbox'}<Checkbox label={customName||'Custom field'} checked={customValue==='true'} onChange={(v)=>customValue=String(v)}/>{:else if customType==='Selection'}<Select label={customName||'Custom field'} options={options('Mara','Narrator','Ensemble')} bind:value={customValue}/>{:else}<Field label={customName||'Custom field'} type={customType==='Date'?'date':customType==='Number'?'number':'text'} bind:value={customValue}/>{/if}</div></div>
{:else if kind==='dialogs'}
<div class="ac-two"><div class="od-stack ac-space"><h4>A focused decision</h4><p>Dialogs preserve context and return focus to their trigger. Escape and the close button offer a clear exit.</p><div class="ka-row"><Button onclick={()=>dialog=true}>Edit project</Button><Button variant="secondary" onclick={()=>confirm=true}>Delete sample</Button></div>{#if deleted}<Notice title="Sample removed" tone="success" message="The change exists only in this example."><Button variant="ghost" onclick={()=>deleted=false}>Undo deletion</Button></Notice>{/if}</div><Menu label="Manuscript actions" items={[{id:'rename',label:'Rename scene'},{id:'history',label:'Draft history',shortcut:'⌘H'},{id:'delete',label:'Delete scene',danger:true}]} onSelect={(id)=>{if(id==='delete')confirm=true;else if(id==='rename')dialog=true;else message='Draft history selected. The application supplies this action.';}}/>{#if message}<p role="status">{message}</p>{/if}</div>
<Dialog bind:open={dialog} title="Project details" subtitle="Simple Story"><div class="od-stack ac-space"><Field label="Title" bind:value={title}/><Field label="Description" multiline value="A short story about returning home."/></div>{#snippet footer()}<Button variant="secondary" onclick={()=>dialog=false}>Close</Button><Button onclick={()=>{dialog=false;message='Project details updated in this example.';}}>Save changes</Button>{/snippet}</Dialog>
<Dialog bind:open={confirm} title="Delete this sample?"><p>You can undo this change after closing the dialog.</p>{#snippet footer()}<Button variant="secondary" onclick={()=>confirm=false}>Cancel</Button><Button variant="danger" onclick={()=>{deleted=true;confirm=false;}}>Delete sample</Button>{/snippet}</Dialog>
{:else if kind==='commands'}
<div class="od-stack ac-space"><div class="ka-between"><div class="od-field"><h4>Find your next action</h4><p class="ka-help">Search, arrow keys, Enter, and Escape are supported.</p></div><Button onclick={()=>commandOpen=true}>Open commands</Button></div><Field label="Filter shortcuts" type="search" bind:value={commandFilter}/>{#if 'find in scene'.includes(commandFilter.toLowerCase())}<ShortcutRecorder label="Find in scene" bind:value={shortcut}/>{:else}<EmptyState title="No matching shortcuts" description="Try “find” or clear the filter." icon="keyboard"/>{/if}{#if message}<Notice title="Command selected" {message}/>{/if}</div>
<CommandPalette bind:open={commandOpen} {commands} onSelect={(id)=>message=`${commands.find(c=>c.id===id)?.label} requested. Connect onSelect to the existing command dispatcher.`}/>
{:else if kind==='search'}
<div class="od-stack ac-space"><div class="ac-two"><Field label="Find" type="search" bind:value={find}/><Field label="Replace with" bind:value={replacement}/></div><p class="ka-help">Searches the sample scene below. Clear the phrase or try another word to explore empty results.</p><SearchResults items={results} query={find} onSelect={()=>dialog=true}/><div class="ka-row"><Button disabled={!results.length} onclick={()=>confirm=true}>Replace all</Button><Button variant="secondary" disabled={previous===null} onclick={()=>{text=previous!;previous=null;message='Replacement undone.';}}>Undo replacement</Button></div>{#if message}<p role="status" class="ka-help">{message}</p>{/if}</div>
<Dialog bind:open={confirm} title="Replace in sample scene?"><p>Replace “{find}” with “{replacement}”. Undo remains available in this specimen.</p>{#snippet footer()}<Button variant="secondary" onclick={()=>confirm=false}>Cancel</Button><Button onclick={replace}>Replace</Button>{/snippet}</Dialog>
<Dialog bind:open={dialog} title="The Beginning"><ManuscriptSurface title="Act 1"><p>{text}</p></ManuscriptSurface></Dialog>
{:else if kind==='statistics'}
<div class="od-stack ac-space"><StatGroup items={[{label:'Project words',value:30},{label:'Today',value:30},{label:'Session',value:words},{label:'Writing streak',value:0,unit:'days'}]}/><Progress label="Daily goal" value={30} max={500}/><div class="ka-row"><Button variant="secondary" onclick={()=>words=0} disabled={words===0}>Reset session</Button><Button variant="secondary" onclick={()=>snapshots=[...snapshots,`Snapshot ${snapshots.length+1}`]}>Create snapshot</Button></div><BeatItem number={1} title="Previously" bind:open={historyOpen}><p>Mara reached the harbor. The letter was still in her coat.</p></BeatItem><Panel title="Draft history">{#if snapshots.length}<div class="od-stack">{#each snapshots as snapshot}<div class="ka-between"><span>{snapshot}</span><Badge label="Saved in example" tone="success"/></div>{/each}</div>{:else}<EmptyState title="No snapshots yet" description="Create a snapshot to keep a named point in this example." icon="history"/>{/if}</Panel></div>
{:else if kind==='editorial'}
<div class="ac-two"><ManuscriptSurface title="Act 1" subtitle="The Beginning"><p>Mara reached the harbor. The lantern shone over the water. She carried the letter home.</p></ManuscriptSurface><Panel title="Review sidebar"><Tabs label="Review panels" items={options('Review','References')} bind:value={reviewTab}>{#snippet children(active)}{#if active==='Review'}<div class="od-stack ac-space">{#if !comments.length}<EmptyState title="No feedback yet" description="Add a comment to begin a local review thread." icon="message-square"/>{:else}{#each comments as c}<Notice title="Review comment" message={c}/>{/each}{/if}<Field label="Comment" multiline bind:value={comment}/><Button disabled={!comment.trim()} onclick={()=>{comments=[...comments,comment.trim()];comment='';}}>Add comment</Button></div>{:else}<EmptyState title="No linked references" description="The app supplies references for the selected passage." icon="book-open"/>{/if}{/snippet}</Tabs></Panel></div>
{:else if kind==='export'}
<div class="od-stack ac-space"><div class="ac-two"><Select label="Export profile" options={options('Agent submission','Reading copy','Custom profile')} bind:value={profile}/><Select label="Output format" options={options('Web / HTML','EPUB','Kindling project','Treatment')} bind:value={format}/></div><div class="ac-export"><NavigationTree label="Export settings" nodes={[{id:'overview',label:'Overview'},{id:'content',label:'Content'},{id:'type',label:'Text & page'}]} bind:selected={exportNav}/><div class="od-stack ac-space">{#if exportNav==='content'}<h4>Choose what goes in.</h4>{#each ['Act 1','Act 2','Act 3'] as act}<Checkbox label={act} checked={selection.includes(act)} onChange={()=>selectChapter(act)}/>{/each}{:else if exportNav==='type'}<h4>Text & page</h4><Select label="Prose family" options={options('Newsreader','Georgia')} value="Newsreader"/><Select label="Text size" options={options('12 pt','14 pt','16 pt')} value="12 pt"/>{:else}<h4>{profile}</h4><p>{format} · {selection.length} acts selected</p><p class="ka-help">This recipe owns export configuration UI. File generation remains in your existing export service.</p>{/if}</div><div class="ac-export-preview">{#if selection.length}<ManuscriptSurface title={selection[0]} subtitle={`${selection.length} acts selected`}><p>Mara reached the harbor. The lantern shone over the water.</p></ManuscriptSurface>{:else}<EmptyState title="Nothing selected yet" description="Choose an act to populate this reading sample." icon="book-open"><Button variant="secondary" onclick={()=>exportNav='content'}>Choose content</Button></EmptyState>{/if}</div></div><div class="ka-between"><Badge label={profile===savedProfile?'Profile unchanged':'Unsaved profile'} tone={profile===savedProfile?'neutral':'warning'}/><div class="ka-row"><Button variant="secondary" onclick={()=>{profile=savedProfile;message='Profile selection reverted.';}}>Revert</Button><Button variant="secondary" onclick={()=>{savedProfile=profile;message='Profile preference saved for this example only.';}}>Save profile</Button><Button disabled={!selection.length} onclick={()=>message=`${format} export requested for ${selection.join(', ')}. Connect this callback to the existing export API; no file was created.`}>Request export</Button></div></div>{#if message}<Notice title="Export configuration" {message}/>{/if}</div>
{/if}
